### ISSUE TITLE
[Request] iSponsorBlock and ReturnYouTubeDislike

### ISSUE THREAD

**Issue by nakhoacool** [swaggyP36000/TrollStore-IPAs#100]
Hey there, is it possible to inject those tweaks into YouTube Reborn?
Thanks

**Comment by ArianaMinajj** [comment]
Hi, 

Spent a few hours attempting to inject both using Azule on Windows (WSL), but this resulted in an "invalid ipa" error, which I'm uncertain as to what it means. Injections with Sideloadly/ESign are both not feasible because iSponsorBlock are dependent on others. 

I'll leave this request open until it's fulfilled either by me or someone else, sorry about that!

**Comment by ArianaMinajj** [comment]
Would you mind testing **[this](https://gofile.io/d/PMt2zP)** and letting me know whether it works?

**Comment by nakhoacool** [comment]
I can confirm that it works. I am using trollstore 2 iPad OS 17.0

**Comment by ArianaMinajj** [comment]
I discovered the reason behind the error. Glad to know it's working on your side!

**Comment by ArianaMinajj** [comment]
We already did
