### ISSUE TITLE
Insta rocket 3.8.3

### ISSUE THREAD

**Issue by gototheskinny** [swaggyP36000/TrollStore-IPAs#11]
Could you please update w/adfree Crack version of this tweak.

**Comment by swaggyP36000** [comment]
Yeah I realized that would probably be better. Was waiting for someone to request it. I'll upload a newer base version with a cracked Rocket as soon as I'm able to get on PC

**Comment by swaggyP36000** [comment]
From what I can find, Rocket cracked works in the InstaRocketPlus IPA, which is the one I opted to update instead, since there was recently an update pushed for that tweaked app. You can just keep all the Plus for Instagram settings disabled and use it as if it was just Rocket cracked for Instagram. Enjoy!

**Comment by gototheskinny** [comment]
> From what I can find, Rocket cracked works in the InstaRocketPlus IPA, which is the one I opted to update instead, since there was recently an update pushed for that tweaked app. You can just keep all the Plus for Instagram settings disabled and use it as if it was just Rocket cracked for Instagram. Enjoy!

Is there a way to get this share option properly work? With tweaked ipas of course 

![image](https://user-images.githubusercontent.com/51786709/213210672-d28666ec-bccb-451e-9a93-3e2d82a45164.png)

**Comment by swaggyP36000** [comment]
Not quite sure. Sometimes it works, sometimes it doesn't. Not sure why that is
