### ISSUE TITLE
is there a backup solution?

### ISSUE THREAD

**Issue by thexYeti** [swaggyP36000/TrollStore-IPAs#111]
hi there, do you have a backup solution in place in case this git gets taken down for whatever reason? 

thanks for maintaining!!

**Comment by ArianaMinajj** [comment]
Hi there,

That's a great question and I must admit that I haven't considered that scenario before. 

However, due to the vast number of updates and ipa files that are hosted in this repo, I'm unable to guarantee a complete backup of the content.. But I will check with the owner a potential solution and keep you updated!

**Comment by swaggyP36000** [comment]
There are no plans for a backup at this time. If the repo ever does go down, go based on the ReadMe to find the latest working versions of the app list from their respective sources, and go from there

It's highly unlikely the repo _will_ ever go down. All credit is given to the respective devs, and we are always welcome to takedown requests if a dev for some reason really doesn't want to see their apps appear here

**Comment by thexYeti** [comment]
good looks, thanks both swaggy and ariana
