### ISSUE TITLE
Is there a way to install Goodnotes 5 or 6 on iPadOS 17.2

### ISSUE THREAD

**Issue by ashwinkhode** [swaggyP36000/TrollStore-IPAs#130]
Hi, I just wanted to know is there any way to install / sideload goodnotes 5 or 6? I know trollstore wont work in iPadOS 17+
I have my dev cert and my iPad is not jailbroken. I tried installing the IPA mentioned in the repo using Esign but it crashes on startup. I am new to Apple ecosystem this is my first apple device so please enlighten me. Thanks

**Comment by ArianaMinajj** [comment]
This shouldn't even be an "issue" because this is TrollStore compatible only. *(Even if it were to work, there was a previous issue mentioned **[here](https://github.com/swaggyP36000/TrollStore-IPAs/issues/93)** where the tweak wouldn't function on iPadOS.)*

Your only remaining option is to utilize Sideloadly with the "Sideload Spoofer" enabled or inject any dylib that might resolve the startup crash.

If this doesn't work, there's nothing more I can do.
