### ISSUE TITLE
[Request] Text Me That

### ISSUE THREAD

**Issue by dvl2014** [swaggyP36000/TrollStore-IPAs#284]
**App Name**: Text Me That
**Request**: Pro Version 
**Appstore Link**: https://apps.apple.com/us/app/text-me-that/id1329223000

- Hi! I just wanted to say thank you so much for your contribution, help, time, and efforts! It would mean so so much if you were able to get Pro for this app, it's very useful especially to me. I normally snooze reminders but this app text you the reminders and I always check my text messages!

**Comment by ArianaMinajj** [comment]
Hello,

Unfortunately, that app is not available in my country and my attempts to log in have failed due to the app claiming my phone number as invalid. 

I still have injected Satella into it and but note if this solution is not working there's not much more I can do.

You can download it **[here](https://gofile.io/d/EfUqH6)**.
