### ISSUE TITLE
Can't load in altstore

### ISSUE THREAD

**Issue by maniac75** [swaggyP36000/TrollStore-IPAs#32]
Hi! Thanks for your great work! It works great on esign but i cant load it in altstore.

"swaggyP36000 IPA Library" could not be added to AltStore. The source "swaggyP36000 IPA Library" contains multiple apps with the bundle identifier com.burn. instagram.

How can i fix it?

Thanks
![image](https://user-images.githubusercontent.com/94304227/224577439-b5f4a2b9-7ad5-4c99-871f-b2f35973717c.png)

**Comment by swaggyP36000** [comment]
This looks like a change made by AltStore. I've tested the repo with AltStore, SideStore (a fork of AltStore that doesn't require a PC to refresh apps), and ESign, and they didn't have problems in the past. SideStore and ESign still loads the repo just fine

AltStore is known for making changes to how source management works for no apparent reason, I'd recommend browsing the source via ESign since you can just download apps from it and export to AltStore or something
