### ISSUE TITLE
[Request] Salatuk - صلاتك

### ISSUE THREAD

**Issue by CiroHoodLove** [swaggyP36000/TrollStore-IPAs#519]
App Name : Salatuk - صلاتك

https://apps.apple.com/us/app/salatuk-%D8%B5%D9%84%D8%A7%D8%AA%D9%83/id686077611

**Comment by ArianaMinajj** [comment]
Hello,

I'll upload it tomorrow!

You can download the latest version **[here](https://gofile.io/d/ESj7zB)** if you prefer not to wait.

**Comment by c12n** [comment]
Did you purchase this and decrypt ? 

It's odd me and you uploaded it and the same time 

- SultanMods

**Comment by CiroHoodLove** [comment]
No he prolly just uploading yours , i was the one that asked for it on your telegram channel , i asked for it a while before here but was rejected although some other paid apps were accepted

**Comment by c12n** [comment]
Odd he didn't credit me lol 

App was paid lol

**Comment by ArianaMinajj** [comment]
> Odd he didn't credit me lol 
> 
> App was paid lol 

Hello,

Sorry for the late reply! I credited your Telegram channel 4 days ago (since I got it from there) but it's been a while already so how did you miss that and still claim that I didn't?

**Comment by c12n** [comment]
Where's the credit? Just want a picture of it 

Check esign ![image](https://github.com/user-attachments/assets/8926fe2a-52c2-4e17-8e03-0050862ff580) dint see it

**Comment by c12n** [comment]
Odd how you removed "sultanmods" from the ipa name

**Comment by ArianaMinajj** [comment]
At this point it seems like you might be trolling? Not only do you misunderstand how the repo works but you also haven't taken the time to read the README.md.

Nonetheless, let me explain: credits for the IPAs are directly mentioned in the repository's README.md and in TrollApps. They aren't in ESing because it **doesn't support it**.

**Please consider verifying your information before commenting or spreading misinformation. I've noticed this behavior from you multiple times, which could eventually lead to a ban from interacting with the repo.**

**Comment by c12n** [comment]
Ok thank you for the explanation
