### ISSUE TITLE
[Request] B612 VIP

### ISSUE THREAD

**Issue by hamidmirza** [swaggyP36000/TrollStore-IPAs#569]
**https://apps.apple.com/us/app/b612-ai-photo-video-editor/id904209370?l**

Thank you for your work.

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/WSJzDE)** if you prefer not to wait.

*Note: I edited your title and initial message because (for the third time) it did not align with the default request template. Kindly make those efforts next time, thank you!*
