### ISSUE TITLE
[Request] OsmAnd Maps+

### ISSUE THREAD

**Issue by thexYeti** [swaggyP36000/TrollStore-IPAs#586]
It’s likely wishful thinking but it would be awesome if OsmAnd Maps could be added with Premium features enabled. 

App Store link: https://apps.apple.com/de/app/osmand-maps-reise-navigation/id934850257

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is already available for this app and I'll upload it in a few hours!

You can download the latest version **[here](https://gofile.io/d/2rrCL1)** if you prefer not to wait.

**Comment by thexYeti** [comment]
Hi, wow, that was quick. Thank you so much!

Would you mind sharing the source of the tweak? 

Most premium features seem to work, but I can’t get unlimited offline maps to work.  Perhaps it works better with an older version. 

Again, I really really appreciate you!

**Comment by ArianaMinajj** [comment]
The tweak's source is explicitly mentioned and I'm afraid that the unlimited offline maps feature is server-sided.. I might have to check that again!

**Comment by thexYeti** [comment]
Sorry, by source I mean where it originated from/who developed it. Or are you the original developer of the tweak itself? Pardon if there’s been a misunderstanding.

**Comment by adrianmihalko** [comment]
I can’t install new maps, anyone have the same problem?

**Comment by guerillafighter** [comment]
I have the same problem, can‘t download any maps at all

**Comment by ArianaMinajj** [comment]
I'm sorry that the tweak doesn't unlock some features such as Travel Guides and unlimited map downloads. However there's a workaround that allows you to download an unlimited amount of maps since this is locally stored. (excluding weather forecast data)

Here's how: **(assuming you have both Filza and TrollStore installed)**

1. Open the app at least once and download a map.

2. Navigate to `/var/mobile/Containers/Data/Application/OsmAnd Maps/Library/Preferences`

3. Locate the `net.osmand.maps.plist` file. Long press on it, select "Open with," and choose "Text Editor".

4. Search for the following line, typically around lines 126 or 127: *(this may vary if you've had the app installed previously)*:


```
   <key>freeMapsAvailable</key>
   <integer>7</integer>
   ```


5. Change the value from `7` to any number you prefer for the number of free downloads, then save the file.
