### ISSUE TITLE
What are the sources of decrypted IPA(s)?

### ISSUE THREAD

**Issue by Infinitay** [swaggyP36000/TrollStore-IPAs#602]
Hello, I was curious as to where you source your ipas from? Do you use decrypt.day or armconverter's ipas, or do you _hypothetically_ decrypt the ipas yourself? Thank you.

**Comment by ArianaMinajj** [comment]
Hello,

It appears obvious that 80% of app updates or new apps are no longer grabbed directly from their sources but decrypted on my own. It’s something I didn't mention before but will in an upcoming repo update! 

I decrypt almost every app thanks to [Apptesters](https://t.me/AppleTesters) and [Decrypted App Store](https://armconverter.com/decryptedappstore). I do not use decrypt.day as this website is known for its intrusive ads, where any adblocking methods need to be removed in order to download anything. (their updates are very outdated anyway so it should be avoided)

Additionally, I also use TrollDecrypt *(since I’m on iOS 17.0)* for apps that do not have widgets or encrypted binaries.

**Comment by Infinitay** [comment]
Thank you for the insightful comment. I was wondering because I was looking for a trustworthy site for decrypted ipas to test dylib injection on my own for some tweaks I wanted to try tweaks that were missing here to see if it's broken or not.
