### ISSUE TITLE
Spring for twitter not working

### ISSUE THREAD

**Issue by nortenootaku** [swaggyP36000/TrollStore-IPAs#66]
Spring for twitter are not working. The app shows an error related to twitter API. But the app continues to receive updates in the app store, maybe you could just update the app so the error could be resolved. thank you very much in advance

**Comment by ArianaMinajj** [comment]
Hello,

I appreciate you reporting the issue regarding "Spring for Twitter" not working. I've looked into it, but unfortunately, I haven't been able to find an updated version.

Until I come across one, the issue will remain open. As a temporary workaround, I recommend using [BHX](https://github.com/swaggyP36000/TrollStore-IPAs/releases?q=BHX&expanded=true).

Thank you for your patience, and I'll keep you posted on any progress. If you have any more questions or concerns, feel free to ask.

**Comment by ArianaMinajj** [comment]
Hello,

I upgraded Spring for Twitter, but honestly it's still a no-go even with the latest update. In fact, it will **never** works even if someone's willing to share the decrypted file.

It seems fine at first right after you install and log in but once you restart, it hits you with this purchase check that just shuts the app down. So I'm still leaving its status as 'not working'. Keeping the app open forever in the background isn't really an option, and I'm not about to pretend otherwise.
