### ISSUE TITLE
[REQUEST] ImgPlay + GIF Maker

### ISSUE THREAD

**Issue by dvl2014** [swaggyP36000/TrollStore-IPAs#730]
**App Name**: ImgPlay: GIF Maker & Meme

**Request**: Premium Unlocked 

**App Store Link**: https://apps.apple.com/us/app/imgplay-gif-maker-meme/id989843523

**Reason**: Been Making GIFs To Send To Friends Often & I Feel Like Many People Use ImgPlay To Do So! 

**Thanks In Advance If You Do Decide To Help With This Request!**

-

**_P.S._** - I Did't Want To Annoy You By Making Another Request Post But If You Can Do Same Request To Another But Similar App:

**App Name** GIF Maker 

**App Store Link**: https://apps.apple.com/us/app/gif-maker-make-video-to-gifs/id1215606098

_Again, Thank You So So Much Again! Not Just For this Request But Everything You Have Done! I Hope You Know Your Hard Work Doesn't Go Unnoticed & Is Always Appreciated!_ 🙂

**Comment by ArianaMinajj** [comment]
Hello,

A tweak is available for both apps and I'll upload them in a few hours. If you prefer not to wait, you can download them **[here](https://gofile.io/d/94fgMb)**.

*Note: Typically, your request would be considered invalid due to multiple submissions at once. However, since both apps are cracked, I have decided to accommodate it.*
