### ISSUE TITLE
Twitch Plus 16.5 | Streams doesn’t work

### ISSUE THREAD

**Issue by TronziaHQ** [swaggyP36000/TrollStore-IPAs#75]
Alright so, basically I was doing my usual Ipa file update. Delete the old and install the new but now this time I get an annoying popup as I open the app and streams doesn’t play and instead displays an error. (I’ve checked on multiple different streams, the same error occurs) as soon as I press on the stream. The chat “loads” but no stream plays.

**Comment by ArianaMinajj** [comment]
Hello,

First of all, thank you for bringing this issue to my attention and for your patience throughout this process. After personally testing the app, I encountered the same issue you described. To address this problem, I've taken the following steps: I rolled back to **[Twitch Plus v16.4](https://github.com/swaggyP36000/TrollStore-IPAs/releases?q=twitch&expanded=true)** and promptly removed the latest release from the repo. It turns out that the IPA I obtained from **[AppleFavour iPA Library](https://t.me/iparsiv)** was indeed flawed, and for this oversight, I sincerely apologize.

I take full responsibility for this situation, and I genuinely regret providing a non-working version in the latest update. Please rest assured that I'm fully committed to rectifying this issue in future releases.

Your feedback and understanding are of great value. If you have any further insights or questions, please don't hesitate to share them.

**Comment by TronziaHQ** [comment]
> Hello,
> 
> First of all, thank you for bringing this issue to my attention and for your patience throughout this process. After personally testing the app, I encountered the same issue you described. To address this problem, I've taken the following steps: I rolled back to **[Twitch Plus v16.4](https://github.com/swaggyP36000/TrollStore-IPAs/releases?q=twitch&expanded=true)** and promptly removed the latest release from the repo. It turns out that the IPA I obtained from **[AppleFavour iPA Library](https://t.me/iparsiv)** was indeed flawed, and for this oversight, I sincerely apologize.
> 
> I take full responsibility for this situation, and I genuinely regret providing a non-working version in the latest update. Please rest assured that I'm fully committed to rectifying this issue in future releases.
> 
> Your feedback and understanding are of great value. If you have any further insights or questions, please don't hesitate to share them.

No worries man, everyone makes mistakes sometimes. Plus Twitch Plus is otherwise really awesome so no worries. I just went back to 16.4 and everything works good as always.

**Comment by ArianaMinajj** [comment]
Streams are now fully functional with the latest version of Twitch Plus (v16.7.2). If this update resolves the issue for you, please consider closing this issue as completed.
