### ISSUE TITLE
What reasons might lead to a source being considered unsafe?

### ISSUE THREAD

**Issue by AleGitMad** [swaggyP36000/TrollStore-IPAs#758]
Sorry to bother you all making a new issue, but I’m actually questioning about how is it possible that sandboxed apps in ios can be malicious. Also I was wondering how did you get that some of the websites found in the readme file are effectively unsafe.

I want to stress that this is asked because of pure curiosity, I don’t want to appear as a know-it-all, on the contrary I really appreciate all of the work you are doing here in mantaining the project and solving all the issues that are raised.

Thanks for your time and kindness in answering this.

**Comment by ArianaMinajj** [comment]
Hello,

Certain websites/sources/entities have been flagged as unsafe for the following reasons:

1. Parties are stealing and redistributing IPAs without the consent of the original creators. These IPAs are often placed behind **a paywall or a donation request**, which is a direct form of exploitation/scam.

2. Parties re-upload *(stole)* IPAs and **inject unknown libraries into them, making it difficult to determine their true purpose.**

The sources marked as UNSAFE have been verified **through unpacking**, revealing that at least one or more of the IPAs have been compromised due to one of the reasons mentioned above.

**Comment by AleGitMad** [comment]
Perfect. Everything’s clear now, thank you so much.
