### ISSUE TITLE
"InstaRocketCracked-305.0-3.8.15.ipa" flagged as Trojan by Windows Defender

### ISSUE THREAD

**Issue by paomck** [swaggyP36000/TrollStore-IPAs#77]
Been using this app for a long time. But the recent update (16th of Oct) triggered defender. It says "Trojan:Script/Wacatac.B!ml"

**Comment by ArianaMinajj** [comment]
Hi there,

I appreciate your patience and diligence in reporting this issue. I've spent some time investigating why the recent update triggered Windows Defender with the "Trojan:Script/Wacatac.B!ml" detection.

Firstly, I'd like to emphasize that I take these concerns seriously and have done my best to ensure the safety of that file. I also conducted a **[VirusTotal Check](https://www.virustotal.com/gui/file/3ad6c0552b939430f30dfa97c92dc0ff32b68fbb12db4781938b492f69026ed2)**.

It's essential to understand that Windows Defender uses machine learning-based detection, which can sometimes generate false positives. In this case, it's possible that this detection might be one of those false positives.

Given that no other antivirus has raised concerns, and the VirusTotal check doesn't reveal any issues, I'm inclined to believe that this is indeed a false positive. If others have encountered a similar issue, please feel free to share your experiences, but for now, I might have to consider closing this issue in the next 24 hours since it appears to be an isolated incident.

Once again, I appreciate your vigilance in keeping the software safe and your understanding in this matter.
