### ISSUE TITLE
Incorrect Watusi version injected into the WhatsApp ipa

### ISSUE THREAD

**Issue by palasser** [swaggyP36000/TrollStore-IPAs#779]
In WhatsApp V24.17.78-1.2.36-3.4.4, Watusi 1.2.32 is injected instead of Watusi 1.2.36 (see attached below).
This removes some handy features (being able to view view-once images on linked devices).

As Watusi V1.2.36 has been injected in a previous IPA, I believe this to be an oversight.

Please inject the new version of Watusi, if you find the time.

Thanks!

![image](https://github.com/user-attachments/assets/5be9c42c-6243-48af-8573-7327a77f95b2)

**Comment by ArianaMinajj** [comment]
Hello,

Thank you so much for letting me know! Watusi updates are really tough to maintain because I personally don't have WhatsApp and have to rely on the sources where the IPAs come from to change the version scheme..

I'll fix that tomorrow!

**Comment by ArianaMinajj** [comment]
I just fixed!

**Comment by palasser** [comment]
> I just fixed it!

Thanks for that!
However, the 2 whatsapp ipas you‘ve uploaded to the source appear to only work on trollstore, while the previous versions supported both.

I know that I am in no way entitled to this, as this is a trollstore repo, but could you maybe also upload a non-trollstore ipa, or direct me to another source that already does so (cracked)?

**Comment by ArianaMinajj** [comment]
I apologize for assuming you were using TS, I've reorganized and reuploaded all the Watusi IPAs providing both cracked and uncracked versions specifically for TS.

Since this repo is intended for TS only I won't be re-uploading sideloaded versions of those IPAs.

However, you might want to consider using this **[source](https://t.me/AppleTesters)** for sideloaded versions. Sorry about that!
