### ISSUE TITLE
[Request] Reeder. Plus

### ISSUE THREAD

**Issue by shy-tangerine** [swaggyP36000/TrollStore-IPAs#784]
### App Store Link

https://apps.apple.com/app/id6475002485

### Feature to Unlock

Reeder+

### Acknowledgment

- [X] I am using TrollStore and requesting an app that I will install with TrollStore.
- [X] This request is not a duplicate and is unique.
- [X] I am aware and agree with my request being closed for one or multiple reasons explained either by labels or a comment.
- [X] I have requested an app that hasn’t been taken down due to takedown removal or DMCA claims.
- [X] I understand that if any of the above conditions are not respected, and this occurs twice in the same month, I will be permanently banned from interacting with the repository.

**Comment by ArianaMinajj** [comment]
Hello,

I won't be uploading this app because it's too specific and the second app you requested **[here](https://github.com/swaggyP36000/TrollStore-IPAs/issues/785)** serves the same purpose. 

However, you can still access this app with all features unlocked via this **[TestFlight invitation](https://testflight.apple.com/join/x4Tc0SfB)**.
