### ISSUE TITLE
Deezer Premium on iOS 15 !

### ISSUE THREAD

**Issue by gtrooper** [swaggyP36000/TrollStore-IPAs#8]
Hello ! I want to say a huge thanks for your amazing work ! Can I just ask if it is possible to incorporate the 2 Deezer DEBS I am attaching into the latest Deezer app from App Store and then create the final IPA ? These 2 files create a perfectly working Deezer Premium App on iOS 14 on Deezer Version 8.37.0.2 ! I cannot update to iOS 15 so I cant test if the latest Deezer works with these 2 DEBS because the latest Deezer requires iOS 15 ! A huge thanks again !

https://mega.nz/file/JloHDDxJ#9RACJOlbRtUZhvZk7zFHOvyKadZ8K31VwzEsBZMaDeI

**Comment by swaggyP36000** [comment]
I've had very bad luck injecting tweak debs into apps on my own, which is why I don't do it often and instead gather a bunch of common tweaked IPAs from different sources. You can request this in the CyPwn server, they can probably get it working for you. And if they choose to upload it to their library, I will upload it here as well

**Comment by gtrooper** [comment]
Oh ! Thanks for the instant answer ! I will have a look !
