### ISSUE TITLE
Noir Trollstore/Filza appsync issue

### ISSUE THREAD

**Issue by gototheskinny** [swaggyP36000/TrollStore-IPAs#83]
Is there a way to use this app without weekly revoking? 
I have trollstore and jb.

**Comment by ArianaMinajj** [comment]
Hi there,

This application is not associated with Trollstore, and I apologize for any confusion caused by not mentioning this earlier.

Regarding functionality, according to feedback from **[Manpreet Singh](https://t.me/AppleTesters)**, it seems that the app's extension is missing with Trollstore.

Additionally, as a potential "solution", you may want to try **[Hyperweb](https://apps.apple.com/us/app/hyperweb/id1581824571)**, a free alternative that also includes a dark mode.

**Comment by gototheskinny** [comment]
> Hi there,
> 
> 
> 
> This application is not associated with Trollstore, and I apologize for any confusion caused by not mentioning this earlier.
> 
> 
> 
> Regarding functionality, according to feedback from **[Manpreet Singh](https://t.me/AppleTesters)**, it seems that the app's extension is missing with Trollstore.
> 
> 
> 
> Additionally, as a potential "solution", you may want to try **[Hyperweb](https://apps.apple.com/us/app/hyperweb/id1581824571)**, a free alternative that also includes a dark mode.

Nitefall works with jb iosgods iap tweak. If you wanna tweak that app and release as an ipa that would be an alternative to this app.

**Comment by gototheskinny** [comment]
@ArianaMinajj Hi! I want to ask about the latest iApps telegram channel version of the Noir app. It's working for me signed with a certificate signer site:(http://ipasharer.cococloud-signing.online)

I **didn't** try WITH **trollstore**

It's has repo's **POPUP** when you first launch the app.

But it works **MOSTLY** (It's settings are not applied correctly to Safari AT ALL(you're stuck with the default settings and dark theme(dark Grey not pitch black)

*I know that the source is a known reposter but it wasn't in the _malicious_ category. This app is very good and overall one of the best Safari **PAID** theme apps. If it's working for safari browser can you please add this to the repo, Thank you 😊.

**Comment by ArianaMinajj** [comment]
Hello,

No, I won't re-introduce into the repo for 2 reasons:

- The IPA from the linked channel has broken keychain groups and encrypted binaries.
- The app is known to be incompatible with TrollStore which is why I removed it some time ago. *(Look at the announcement part)*

The only reliable source to obtain IPAs such as this app is on **[AppCake](https://www.iphonecake.com/app_1581140954_.html)**.

**Comment by gototheskinny** [comment]
> Hello,
> 
> No, I won't re-introduce this app into the repo for 2 reasons:
> 
> - The IPA from the linked channel has broken keychain groups and encrypted binaries.
> - The app is known to be incompatible with TrollStore which is why I removed it some time ago. *(Look at the announcement part)*
> 
> The only reliable source to obtain IPAs such as this app is on **[AppCake](https://www.iphonecake.com/app_1581140954_.html)**.

OK i get it, thank you for your reply 😊
