### ISSUE TITLE
iGGod's decrypt tool does not work on TrollStore 15.5+

### ISSUE THREAD

**Issue by MathieDev** [swaggyP36000/TrollStore-IPAs#86]
I'm on 16.1 on an A12 device right, and the app launches alright and I can decrypt ipa, except that the apps aren't being modified when I enable them. Help would be appreciated, thanks!

Also, please don't scream at me because the apps might not have been updated for other versions, just reporting this issue so it can be known, thanks!

**Comment by ArianaMinajj** [comment]
Hi there, 

When you say that "apps aren’t being modified" when enabled, are you referring to the apps not being decrypted properly or behaving unusually post-decryption? In my tests, I've seen that decrypted apps with iGameGod are not decrypting as expected, which causes the applications to close right after startup. This might be due to the fact that decryption typically requires a jailbroken device.. Could you please provide more information on what exactly you're experiencing?

**Comment by MathieDev** [comment]
What I meant is that the iGameGod button isn't showing up inside the apps so it's not injecting properly.

**Comment by ArianaMinajj** [comment]
I'm experiencing the same issue. This could be due to a variety of reasons, including an issue with the iGG tool itself, or a compatibility problem with TrollStore 2.

I suggest to use alternative methods such as Sideloadly or ESign which could indeed be a viable solution if you have the iGG tweak file to inject.

**Comment by ArianaMinajj** [comment]
I found that you **must** use iGameGod jailed since the IPA file appears to function exclusively on jailbroken devices. This concern was highlighted in detail **[here](https://www.reddit.com/r/sideloaded/comments/100svvv/how_can_i_install_igamegod/)**, so please review it attentively. I will change the status of the app or potentially remove it.
